added * for mandatory fields
Real-Dev-Squad/website-my pull request #137
Opened 2021-08-25 07:17 UTC by Hitendra10

2021-08-30 13:35 UTC, Hitendra10 commented on app/controllers/signup.js
> +      label: 'First Name. *',
should i remove the dots?

2022-02-05 17:38 UTC, swarajpure requested changes
There is an open comment on this PR
@Hitendra10 are you still working on this?

2022-02-26 08:55 UTC, Hitendra10 commented
No, i am no longer working on this.

2022-08-17 12:21 UTC, rohan09-raj commented
Closing the Pull Request as the author is no longer working on the PR
https://github.com/Real-Dev-Squad/website-my/pull/137#issuecomment-1051857396

2022-08-17 12:21 UTC, closed without merging