Signup flow
Real-Dev-Squad/website-my pull request #246
Opened 2022-08-05 20:11 UTC by shreya-mishra

![image](https://user-images.githubusercontent.com/61110378/183155818-dd85778c-889e-487e-815c-f98d9454c2fb.png)

2022-08-06 01:16 UTC, MehulKChaudhari reviewed
Congrats on learning testing. I have added comments please a have look.

2022-08-06 01:16 UTC, MehulKChaudhari commented on tests/acceptance/signup-flow-test.js
> +    assert.dom('[data-test-id="form-input-last_name"]').hasProperty('value','user')
`hasProperty` checks the properties of the selected HTML element, `hasProperty` is used to check let's say whether the input field is a type password or a normal input field etc. 

To check the value of input `hasValue` is the assertion to use.

2022-08-06 01:16 UTC, MehulKChaudhari commented on tests/acceptance/signup-flow-test.js
> +  test('http://localhost:4200/signup', async function(assert) {
I think a more descriptive name test name will be good instead of `http://localhost:4200/signup`

2022-08-06 01:16 UTC, MehulKChaudhari commented on tests/acceptance/signup-flow-test.js
> +    const fields = {
nit: We can move `fields` to mocks folder.

2022-08-06 17:39 UTC, ankushdharkar requested changes

2022-08-06 17:39 UTC, ankushdharkar commented on tests/acceptance/signup-flow-test.js
> +    window.alert = originalWindowAlert;
Why does the test have an alert? 🤔 

What does this do for our assertions?

2022-08-06 17:39 UTC, ankushdharkar commented on app/components/form-input.hbs
> +    data-test-id="form-input-{{@id}}"
This can be a static named id, so that we can easily grab it in the tests.
```suggestion
    data-test-id="form-input"
```

2022-08-06 17:39 UTC, ankushdharkar commented on app/templates/signup.hbs
> +        data-test-id='signup-button-disabled'
The state of the button changes, so we should not use that to identity the element here
```suggestion
        data-test-id='signup-submit-button'
```

2022-08-06 17:39 UTC, ankushdharkar commented on app/templates/signup.hbs
> +        data-test-id='signup-button-disabled'
I see. This challenge that you faced comes from https://github.com/Real-Dev-Squad/website-my/pull/238#discussion_r930579530

2022-08-06 17:43 UTC, ivinayakg reviewed
On starting with testing 🤩
"Welcome to the mafia"

2022-08-06 17:43 UTC, ivinayakg commented on tests/acceptance/signup-flow-test.js
> +    window.alert = function() { return true;}
do we need this?
(im not sure 100% honestly)

2022-08-06 17:43 UTC, ivinayakg commented on tests/acceptance/signup-flow-test.js
> +
can there also be something like clicking the button and then disabling it, and checking for the same?

2022-11-22 14:51 UTC, closed without merging

2022-11-22 14:52 UTC, rohan09-raj commented
New PR has been raised for the same issue https://github.com/Real-Dev-Squad/website-my/pull/269