Feat/user status modal
Real-Dev-Squad/website-my pull request #341
Opened 2022-12-15 04:18 UTC by heyrandhir

Closes all the points in https://github.com/Real-Dev-Squad/website-my/issues/340 except the 3rd one realted to future status.

- [x] Currently, Users can select any date while marking themselves as `Idle or Active`. We need to remove the `from date` field for `Idle or Active`. The `from date` field value will be the date on which they mark themselves as `Idle or Active`.  
- [x] Submit Button to enable only when all the mandatory fields are selected 
- [ ] If the users mark themselves `OOO` for a Future Date. It overrides the current status and shows `You are OOO`. It should show `OOO` only once the date arrives. Handle this case and also figure out what happens once the user is back in the office. 
- [x] If the Users are `OOO` for less than 3 days `Reason` shouldn't be mandatory. 
- [x] Disable past date selection for `OOO`

2022-12-17 06:55 UTC, rohan09-raj requested changes

2022-12-17 06:55 UTC, rohan09-raj commented on app/components/user-status-modal.js
> +      return timeGap <= 172800000;
Can we have it in constants please ?

2022-12-17 06:55 UTC, rohan09-raj commented on app/components/user-status-modal.hbs
> +      {{else if (eq @newStatus 'IDLE')}}
You can use the constants here for `IDLE` by defining the constant in the component file.

2022-12-17 06:55 UTC, rohan09-raj commented on app/components/user-status-modal.hbs
> +
Can we remove this extra line spaces?

2022-12-17 06:55 UTC, rohan09-raj commented on app/components/user-status.js
> +      const activeStateObj = {
Can we name as `activeState` only as it's obvious that it's a object by reading the code

2022-12-19 05:09 UTC, MehulKChaudhari approved these changes

2022-12-19 13:12 UTC, rohan09-raj commented on app/components/user-status-modal.js
> +  checkSubmitBttnState() {
Type : Bttn => Btn

2022-12-19 13:12 UTC, rohan09-raj commented on app/components/user-status-modal.js
> +    this.checkSubmitBttnState();
Type : Bttn => Btn

2022-12-19 13:13 UTC, rohan09-raj commented on app/components/user-status-modal.js
>      } else if (name === 'reason') {
I think we can use constants here.

2022-12-27 16:32 UTC, rohan09-raj approved these changes
Great work 🔥

2022-12-27 16:32 UTC, merged

2023-01-04 00:07 UTC, heyrandhir commented
the 3rd point `If the users mark themselves OOO for a Future Date. It overrides the current status and shows You are OOO. It should show OOO only once the date arrives. Handle this case and also figure out what happens once the user is back in the office.` changes are active in the backend.