added ONBOARDING userstate to render userStatus UI
Real-Dev-Squad/website-my pull request #394
Opened 2023-04-26 01:38 UTC by shubhamsigdar1

2023-05-08 04:57 UTC, RitikJaiswal75 commented on app/styles/user-status.css
> +  box-shadow: 0 0 15px -7px var(--onboarding-card--box-shadow);
please try not to use odd numbers for pixel size

2023-05-08 15:57 UTC, heyrandhir requested changes

2023-05-08 15:57 UTC, heyrandhir commented on app/components/user-status.hbs
> +    <h2 data-test-status>{{currentStatus.message}}</h2>
should this be in the `else`. i.e if the status is `onboarding` then we shouldn't show this. Right ?

2023-05-13 00:10 UTC, RitikJaiswal75 reviewed
Please write tests for it

2023-05-15 02:10 UTC, RitikJaiswal75 approved these changes

2023-05-15 02:11 UTC, heyrandhir approved these changes

2023-05-15 02:12 UTC, heyrandhir commented
Approving it for now as this was one off exception. Please write the tests ASAP.

2023-05-15 02:20 UTC, merged