feat-update flow for marking user idle
Real-Dev-Squad/website-my pull request #413
Opened 2023-06-18 00:42 UTC by manish591

2023-06-19 01:30 UTC, heyrandhir commented
Can you attach a video @manish591 showing the flow. that will be helpful

2023-06-19 02:18 UTC, heyrandhir requested changes

2023-06-19 02:18 UTC, heyrandhir commented on app/components/user-status-modal.hbs
> +      </label>
We utilize the constants ACTIVE and IN_PROGRESS to represent specific states. When displaying a user message, we can present it in regular lowercase format.

2023-06-19 02:18 UTC, heyrandhir commented on app/components/user-status.js
> +          userStatus = 'ACTIVE';
Nit: once matched we can break from here

2023-06-19 02:18 UTC, heyrandhir commented on app/controllers/index.js
> +            console.log('response', responseData);
we can remove the log message

2023-06-19 02:25 UTC, heyrandhir commented
@manish591 I think once the user is assigned a task then too we need to change the status to active on the backend. Since on completion we are changing their status to `idle`

2023-06-19 13:55 UTC, manish591 commented
> @manish591 I think once the user is assigned a task then too we need to change the status to `active` on the backend. Since on completion we are changing their status to `idle`

Yes right, but I faced a blocker in doing so. Can we discuss this?

2023-06-19 15:49 UTC, heyrandhir requested changes
The tests seems to be missing. will that be a separate PR @manish591

2023-06-20 00:36 UTC, heyrandhir requested changes
Hello @manish591, during the morning scrum today, I talked with @ankushdharkar about the idea of making the user switch to an `idle` state once their task has been marked as completed. We concluded that this logic should be implemented on the backend instead of the frontend.

2023-06-24 15:22 UTC, closed without merging