cancel OOO button enabled
Real-Dev-Squad/website-my pull request #500
Opened 2023-10-11 02:56 UTC by PeeyushPrashant

What is the change?
cancel OOO button added when user status is OOO

Issue -https://github.com/Real-Dev-Squad/website-my/issues/495

2023-10-12 10:31 UTC, shubhamsigdar1 commented
### Issue

##### Example : Closes #<issue_number>

### What is the change?

Provide a small description in points of what did you change

##### Example :

- Done this
- Made these changes

### Is Development Tested?

- [x] Yes
- [ ] No

### Before / After Change Screenshots

For visual or interaction changes. Please provide a video / screenshot.

##### Example:

Before :
Image/Video

After :
Image/Video

**Note :**
What to delete and what not to

- Keep the headings and answer the questions.
- Delete the examples
- Delete the description below headings `What is the change?` & `Before/After Screenshots`

**Can you please fill above in description**

2023-10-12 11:50 UTC, PeeyushPrashant reviewed
Thanku @shubhamsigdar1 for these inputs, I have added them now.

2023-10-12 11:55 UTC, PeeyushPrashant commented
Thanku @shubhamsigdar1 for these inputs, I have added them now.

2023-10-12 13:36 UTC, shubhamsigdar1 reviewed
Can you please attach video in description
in which you show -1. you change your status to OOO then cancel OOO button visible and then when you click on Cancel OOO button another status will be shown on page with OOO status button 

and also try make current status OOO and future status ACTIVE in backend database 
then when you click cancel OOO then your status change to active

2023-10-12 13:46 UTC, shubhamsigdar1 reviewed
pr look good to me
just make that video I will approve it

2023-10-12 15:06 UTC, shubhamsigdar1 approved these changes

2023-10-13 04:20 UTC, iamitprakash requested changes
please follow PR details format

2023-10-13 04:38 UTC, shubhamsigdar1 requested changes
Feature under feature flag

2023-10-13 13:18 UTC, shubhamsigdar1 commented on app/templates/index.hbs
> +{{/if}}
Does <UserStatus /> required to write two times
if @dev=false pass then cancel ooo button not render
if @dev=true pass then cancel ooo button render

2023-10-13 13:18 UTC, shubhamsigdar1 commented on tests/integration/components/user-status-test.js
> +  test('show relevant data when status is OOO and dev is false', async function (assert) {
```suggestion
  test('show relevant data when status is OOO  and not have feature flag', async function (assert) {
```

2023-10-13 13:18 UTC, shubhamsigdar1 commented on tests/integration/components/user-status-test.js
> +  test('show relevant data when status is OOO and dev is true', async function (assert) {
```suggestion
  test('show relevant data when status is OOO and have feature flag', async function (assert) {
```

2023-10-13 13:22 UTC, shubhamsigdar1 commented on app/templates/index.hbs
> +{{/if}}
```suggestion
{{#if this.isDevMode}}
  <UserStatus 
    @status={{this.status}} 
    @changeStatus={{this.changeStatus}}
    @dev={{this.isDevMode}} 
    @isStatusUpdating={{this.isStatusUpdating}}
    @updateStatus={{this.updateStatus}}
  />
```

2023-10-13 14:12 UTC, shubhamsigdar1 approved these changes

2023-10-13 14:37 UTC, Pratiyushkumar approved these changes

2023-10-13 16:40 UTC, heyrandhir approved these changes

2023-10-13 16:55 UTC, merged