dev to main sync
Real-Dev-Squad/website-my pull request #523
Opened 2023-11-22 18:56 UTC by shubhamsigdar1

Date: 23-11-2023

Developer Name: @shubhamsigdar1 

## Issue Ticket Number:- 

- https://github.com/Real-Dev-Squad/website-my/issues/521

## PR Number(s):-

- https://github.com/Real-Dev-Squad/website-my/pull/522

Is Under Feature Flag 
- [ ] Yes
- [X] No

Database changes
- [X] Yes
- [ ] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)
- [ ] Yes
- [x] No

Is Development Tested?

- [x] Yes
- [ ] No

Tested in staging?

- [x] Yes
- [ ] No

Add relevant Screenshot below

https://github.com/Real-Dev-Squad/website-my/assets/107163260/c8c3c565-3f59-40f3-a491-d43ff88e12cf

2023-11-22 19:37 UTC, shubhamsigdar1 commented
Date: 23-11-2023

Developer Name: @dhruv036 

## Issue Ticket Number:- 

- https://github.com/Real-Dev-Squad/website-my/issues/501

## PR Number(s):-

- https://github.com/Real-Dev-Squad/website-my/pull/506


Is Under Feature Flag 
- [X] Yes
- [ ] No

Database changes
- [ ] Yes
- [X] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)
- [ ] Yes
- [x] No

Is Development Tested?

- [x] Yes
- [ ] No

Tested in staging?

- [x] Yes
- [ ] No

Add relevant Screenshot below

2023-11-22 19:40 UTC, dhruv036 commented
> Date: 23-11-2023
> 
> Developer Name: @dhruv036
> 
> ## Issue Ticket Number:-
> * [Open RDS app from My-site #501](https://github.com/Real-Dev-Squad/website-my/issues/501)
> 
> ## PR Number(s):-
> * [Added Open RDS app from my-site #506](https://github.com/Real-Dev-Squad/website-my/pull/506)
> 
> Is Under Feature Flag
> 
> * [x]  Yes
> * [ ]  No
> 
> Database changes
> 
> * [ ]  Yes
> * [x]  No
> 
> Breaking changes (If your feature is breaking/missing something please mention pending tickets)
> 
> * [ ]  Yes
> * [x]  No
> 
> Is Development Tested?
> 
> * [x]  Yes
> * [ ]  No
> 
> Tested in staging?
> 
> * [x]  Yes
> * [ ]  No
> 
> Add relevant Screenshot below


https://github.com/Real-Dev-Squad/website-my/assets/56362412/f255b0f0-ec62-4115-8dba-75a591e9809d

2023-11-22 20:04 UTC, yesyash requested changes

2023-11-22 20:04 UTC, yesyash commented on app/templates/application.hbs
> +@deviceType = {{this.toVisible}}
- we are passing a boolean here should we change the prop name from `deviceType` to something more representative of the value being passed?

2023-11-22 20:04 UTC, yesyash commented on app/styles/components/mobile-dialog.css
> +    border-radius: 3px;
- as the rds design system has a base unit of `4px` please use multiples of 4 here (4, 8, 16, ...)

2023-11-22 20:04 UTC, yesyash commented on app/styles/components/mobile-dialog.css
> +      border-radius: 3px;
- please use multiples of 4 here.

2023-11-22 20:06 UTC, yesyash requested changes

2023-11-22 20:06 UTC, yesyash commented on app/components/mobile-dialog.hbs
> +      <button id="mobile-dialog__close-button" type="button" {{on 'click' (fn this.closeDialog)}} >Cancle</button>
```suggestion
      <button id="mobile-dialog__close-button" type="button" {{on 'click' (fn this.closeDialog)}} >Cancel</button>
```

2023-11-22 20:08 UTC, yesyash requested changes

2023-11-22 20:08 UTC, yesyash commented on app/components/mobile-dialog.hbs
> +        Open RDS in app
```suggestion
        Open in RDS App
```

2023-11-24 10:47 UTC, sumitd94 approved these changes

2023-11-24 10:50 UTC, merged