navbar added
Real-Dev-Squad/website-my pull request #77
Opened 2021-04-09 16:49 UTC by adnanraghib1308

2021-04-13 11:29 UTC, swarajpure requested changes
Tried to give solution to the fests failing and asking to add a new page `/tasks`
Please check!

Thank you! 🎉

2021-04-13 11:29 UTC, swarajpure commented on app/components/nav-bar.hbs
> +    </ul>
Please add `/tasks` as well

2021-04-13 11:29 UTC, swarajpure commented on app/styles/navbar.css
> +}
How is this looking on mobile phones? 🤔

2021-04-13 11:29 UTC, swarajpure commented on tests/integration/components/nav-bar-test.js
> +    assert.equal(this.element.textContent.trim(), '');
See you're rendering Navbar, it has text `Home` and `Signup` now
And you're checking if that's equal to `''` which is causing the tests to fail and hence the github checks to fail
Please check

2021-07-03 18:51 UTC, ankushdharkar commented
Closing this in favour #87

2021-07-03 18:51 UTC, closed without merging