[WIP] Local Navbar for internal navigation
Real-Dev-Squad/website-my pull request #87
Opened 2021-04-28 16:21 UTC by swarajpure

2021-05-14 18:58 UTC, swarajpure commented
![image](https://user-images.githubusercontent.com/56217868/118316317-4d8d2080-b514-11eb-95d0-06272b0522aa.png)

On Hover:

![image](https://user-images.githubusercontent.com/56217868/118316362-5c73d300-b514-11eb-9465-ca6cd2d8eef0.png)

2021-07-01 18:18 UTC, swarajpure commented
New screenshots are updated in the PR description

2021-07-02 01:15 UTC, prakashchoudhary07 submitted a review, later dismissed

2021-07-11 19:59 UTC, ankushdharkar requested changes

2021-07-11 19:59 UTC, ankushdharkar commented on app/components/local-navbar.hbs
> +  </p>
Should this be a <span> like the rest?

2021-07-11 20:01 UTC, swarajpure commented
- Remove `signup`
- Let the navbar elements come from a list of objects

2021-07-11 20:18 UTC, merged